### ISSUE TITLE
snakemake run error 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pipeline-polya-diff#1]
I am was interested to run this comparison between nanopolish outputs. I have the filtered.tsv files. An example is below. 

config file 

`
  GNU nano 2.9.3                                                                                       config.yml                                                                                                  

[Book1.xlsx](https://github.com/nanoporetech/pipeline-polya-diff/files/4539071/Book1.xlsx)

---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-polya-diff"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-polya-diff"

## Pipeline-specific parameters:

# Control tail estimates
control_tails:
    wt_1: "data/test.polya.estimation.tsv"
    wt_2: "data/test.polya.estimation_2.tsv"

# Treated tail estimates
treated_tails:
    mut_1: "data/test2.polya.estimation.tsv"
    mut_1: "data/test2.polya.estimation_2.tsv"

# Minimum reads per transcript
min_reads_per_transcript: 5

# Generate per-transcript plots
per_transcript_plots: "true"

# Threads
threads: 12
`

`
(base) minion@TM1803:~/pipeline-polya-diff$ snakemake --use-conda -j 12 all
RuleException in line 30 of /home/minion/pipeline-polya-diff/Snakefile:
Conda environments are only allowed with shell, script, notebook, or wrapper directives (not with run).
  File "/home/minion/pipeline-polya-diff/Snakefile", line 30, in <module>`

**Comment by bsipos** [comment]
This is an issue with the latest snakemake release. Fixed in the master of the pipeline, please update and try again.

**Comment by callumparr** [comment]
I think I was already up to date with the master. Is there some commit recently?

**Comment by bsipos** [comment]
Sorry, pushed to the wrong remote. Now it should be there. :)
