### ISSUE TITLE
issue with running pipeline-polya-diff !

### ISSUE THREAD

**Issue by g-s-2018** [nanoporetech/pipeline-polya-diff#2]
Hi,
I have edited the config.yml and I am not sure what is the problem.

~/tools/pipeline-polya-diff$ snakemake --use-conda -j 56  all
AttributeError in line 6 of~tools/pipeline-polya-diff/Snakefile:
'Workflow' object has no attribute 'overwrite_configfile'
  File "~/tools/pipeline-polya-diff/Snakefile", line 6, in <module>

Any help, 
Thanks

**Comment by m-noonan** [comment]
Hi, I'm having the same issue, how did you resolve this?

**Comment by g-s-2018** [comment]
Unfortunately, no one responded back to me to solve this issue.
